# typed: false
# frozen_string_literal: true

# This file is generated by the abs-mcp release workflow - do not edit by hand.
class AbsMcp < Formula
  desc "MCP server and CLI for curating an Audiobookshelf library"
  homepage "https://github.com/katbyte/abs-mcp"
  url "https://github.com/katbyte/abs-mcp/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "33102507099c9fa7d6f18c41b2d07b11f439bd435b696255df8b4d9f7ee02ba6"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/abs-mcp.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/abs-mcp/lib/version.Version=v0.1.0 -X github.com/katbyte/abs-mcp/lib/version.GitCommit=homebrew")
  end

  test do
    assert_match "v0.1.0", shell_output("#{bin}/abs-mcp version")
  end
end
