# typed: false
# frozen_string_literal: true

# This file is generated by the abs-mcp release workflow - do not edit by hand.
class AbsMcp < Formula
  desc "MCP server and CLI for curating an Audiobookshelf library"
  homepage "https://github.com/katbyte/abs-mcp"
  url "https://github.com/katbyte/abs-mcp/archive/refs/tags/v0.6.0.tar.gz"
  sha256 "e7f8280a9fb4764c3ebb2e04f5446f75b35649998d2de96db6416e1ece2612b1"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/abs-mcp.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/go-kt/version.Version=v0.6.0 -X github.com/katbyte/go-kt/version.GitCommit=homebrew")
  end

  test do
    assert_match "v0.6.0", shell_output("#{bin}/abs-mcp version")
  end
end
