# typed: false
# frozen_string_literal: true

# This file is generated by the acorn-vfd release workflow - do not edit by hand.
class Acornvfd < Formula
  desc "Control the Acorn Workshop XGGF-1V48 VFD clock over Bluetooth LE"
  homepage "https://github.com/katbyte/acorn-vfd"
  url "https://github.com/katbyte/acorn-vfd/archive/refs/tags/v0.1.1.tar.gz"
  sha256 "54553710496e1b277525e2c146044d72e93975b8414e0b7e8ed91d739ba2b16f"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/acorn-vfd.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/acornvfd/lib/version.Version=v0.1.1 -X github.com/katbyte/acornvfd/lib/version.GitCommit=homebrew")
  end

  test do
    assert_match "v0.1.1", shell_output("#{bin}/acornvfd version")
  end
end
