# typed: false
# frozen_string_literal: true

# This file is generated by the embyfin-mcp release workflow - do not edit by hand.
class EmbyfinMcp < Formula
  desc "MCP server and CLI for curating Emby and Jellyfin media libraries"
  homepage "https://github.com/katbyte/embyfin-mcp"
  url "https://github.com/katbyte/embyfin-mcp/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "38b15db39033ef5f2ddd1c1bccd625d510fe84c32aac52fdff3eeadf2360a1f2"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/embyfin-mcp.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/go-kt/version.Version=v0.2.0 -X github.com/katbyte/go-kt/version.GitCommit=homebrew")
  end

  test do
    assert_match "v0.2.0", shell_output("#{bin}/embyfin-mcp version")
  end
end
