# typed: false
# frozen_string_literal: true

# This file is generated by the embyfin-mcp release workflow - do not edit by hand.
class EmbyfinMcp < Formula
  desc "MCP server and CLI for curating Emby and Jellyfin media libraries"
  homepage "https://github.com/katbyte/embyfin-mcp"
  url "https://github.com/katbyte/embyfin-mcp/archive/refs/tags/v0.5.0.tar.gz"
  sha256 "42e3b02720a9de4bc69345e9e92aec87353f3d595d93dc63877eaec6c26b3220"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/embyfin-mcp.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/go-kt/version.Version=v0.5.0 -X github.com/katbyte/go-kt/version.GitCommit=homebrew")
  end

  test do
    assert_match "v0.5.0", shell_output("#{bin}/embyfin-mcp version")
  end
end
