# typed: false
# frozen_string_literal: true

# This file is generated by the ghp-sync release workflow - do not edit by hand.
class GhpSync < Formula
  desc "Sync GitHub issues and PRs to a GitHub Project"
  homepage "https://github.com/katbyte/ghp-sync"
  url "https://github.com/katbyte/ghp-sync/archive/refs/tags/v0.3.2.tar.gz"
  sha256 "34a1067f12c8b4cc582a923de63948855cfb841b3e9c7233cf37d1c7e57378e9"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/ghp-sync.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/go-kt/version.Version=v0.3.2 -X github.com/katbyte/go-kt/version.GitCommit=homebrew")
  end

  test do
    assert_match "v0.3.2", shell_output("#{bin}/ghp-sync version")
  end
end
