# typed: false
# frozen_string_literal: true

# This file is generated by the radarr-mcp release workflow - do not edit by hand.
class RadarrMcp < Formula
  desc "MCP server and CLI for curating a Radarr film library"
  homepage "https://github.com/katbyte/radarr-mcp"
  url "https://github.com/katbyte/radarr-mcp/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "a2858060fe235d27fa24f4b8e2ebe94b5272f6afc8baf7bd48f46e95d8b11de7"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/radarr-mcp.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/go-kt/version.Version=v0.2.0 -X github.com/katbyte/go-kt/version.GitCommit=homebrew")
  end

  test do
    assert_match "v0.2.0", shell_output("#{bin}/radarr-mcp version")
  end
end
