# typed: false
# frozen_string_literal: true

# This file is generated by the radarr-mcp release workflow - do not edit by hand.
class RadarrMcp < Formula
  desc "MCP server and CLI for curating a Radarr film library"
  homepage "https://github.com/katbyte/radarr-mcp"
  url "https://github.com/katbyte/radarr-mcp/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "643d1aa2c0667d89c64aa016bae44ab3937c3f8be3a83f42f876f0fd30d0176c"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/radarr-mcp.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/go-kt/version.Version=v0.1.0 -X github.com/katbyte/go-kt/version.GitCommit=homebrew")
  end

  test do
    assert_match "v0.1.0", shell_output("#{bin}/radarr-mcp version")
  end
end
