# typed: false
# frozen_string_literal: true

# This file is generated by the sonarr-mcp release workflow - do not edit by hand.
class SonarrMcp < Formula
  desc "MCP server and CLI for running and auditing a Sonarr TV library"
  homepage "https://github.com/katbyte/sonarr-mcp"
  url "https://github.com/katbyte/sonarr-mcp/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "2a03686ebb56481a76d3271a159ee195745dfa7a117639cd87b8a35e2a242cac"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/sonarr-mcp.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/go-kt/version.Version=v0.1.0 -X github.com/katbyte/go-kt/version.GitCommit=homebrew")
  end

  test do
    assert_match "v0.1.0", shell_output("#{bin}/sonarr-mcp version")
  end
end
