# typed: false
# frozen_string_literal: true

# This file is generated by the taproot release workflow - do not edit by hand.
class Taproot < Formula
  desc "Back up, copy and control Nanoleaf Light Panels scenes over the local API"
  homepage "https://github.com/katbyte/nanoleaf-aurora-taproot"
  url "https://github.com/katbyte/nanoleaf-aurora-taproot/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "fac481d2421b3c53674e49877921293b79ac7ffbb2ba019718a3342e29bb6f69"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/nanoleaf-aurora-taproot.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/go-kt/version.Version=v0.2.0 -X github.com/katbyte/go-kt/version.GitCommit=homebrew"), "./cmd/taproot"
  end

  test do
    assert_match "v0.2.0", shell_output("#{bin}/taproot version")
  end
end
